### ISSUE TITLE
Computer Control via USB

### ISSUE THREAD

**Issue by pauldw** [pauldw/inflatinator-firmware#13]
Make the Inflatinator controllable with a computer via USB, for advanced use cases (e.g. balloon structures) and prototyping features that are planned for including on-device later (e.g. randomizer).

To simplify the experience, the Inflatinator should have a "USB control mode".  This mode could be entered if the USB serial port device is connected.  See http://arduino.cc/en/Serial/IfSerial .

This mode can be exited if the USB serial port device is disconnected.

In the USB control mode, the Inflatinator receives inflate commands.  The Inflatinator asynchronously sends pedal events.

Inflate command:
(a time in mS) (b time in mS)\n
1000 2000\n
A at 1 second, B at 2 seconds
Inflation starts automatically after times are sent.

Pedal event:
PEDAL_PRESS\n

Future work can include additional events (pedal_up, inflate_start, inflate_end) and commands (get_status, stop_inflate), but this should be a good start.

**Comment by pauldw** [comment]
Estimate: 4h.

**Comment by DrewRipley** [comment]
This sounds like a good plan. Plus it would allow for further programming (and testing) at the computer before making it a permanent firmware upgrade. Sounds great!

**Comment by pauldw** [comment]
This is working now in the feat/remote branch.
